#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
#!/bin/sh
menuentry "Arch" {
        insmod fat
        insmod chain
        search --no-floppy --set=root --fs-uuid D283-1165
        chainloader /EFI/arch/grubx64.efi
}
menuentry "OpenSUSE" {
        insmod fat
        insmod chain
        search --no-floppy --set=root --fs-uuid D283-1165
        chainloader /EFI/opensuse/grubx64.efi
}
menuentry "Debian" {
        insmod fat
        insmod chain
        search --no-floppy --set=root --fs-uuid D283-1165
        chainloader /EFI/debian/grubx64.efi
}
menuentry 'Desligar' {
        halt
}
menuentry 'Reiniciar' {
        reboot
}
